config/routes.rb
Rails.application.routes.draw do

  root :to =>  'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'manage/dashboard'

  namespace :manage do
    resources :books do
      get :sort_posts, :on => :member
      get :sort_volumes, :on => :member
      resources :volumes do
        get :update_name, :on => :member
        get :update_description, :on => :member
      end
      resources :posts, :except => [:show] do
        get :release, :on => :member
        get :withdraw, :on => :member
      end
    end
  end

  resources :books, only: [:show] do
    get :query_post, :on => :member
  end

  #profile => author
  get 'complete_your_information', :to =>"profile#new" 
  get 'edit_profile', :to => "profile#edit"
  patch 'profile/update'
  patch 'profile/update_avatar'
  get 'profile/update'
  get 'profile/update_avatar'
  post 'profile/create'

end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :user
  has_many :books

  mount_uploader :file_avatar, AvatarUploader

  validates :name, presence: true

  def can_create_book?
    self.books.size < 8
  end
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :category, presence: true

  has_many :posts, dependent: :destroy
  has_many :volumes, dependent: :destroy
  belongs_to :author

  mount_uploader :file_cover, CoverUploader
end

app/models/bucket.rb
class Bucket < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book

  validates :name, presence: true
  validates :email, presence: true
  validates :content, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  validates :from, presence: true
  validates :to, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :category, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :recipient, presence: true
  validates :sender, presence: true
  validates :reply_to, presence: true
end

app/models/piece.rb
class Piece < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :book
  belongs_to :volume

  validates :title, presence: true
  validates :content, presence: true
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :author
end

app/models/volume.rb
class Volume < ApplicationRecord
  belongs_to :book
  has_many :posts
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
  def get_avatar(author, size="", cl="")
    img = ""
    if author.file_avatar.blank?
      url = "avatar/" + author.avatar_id.to_s + ".png"
    else
      url = author.file_avatar.url(:thumb)
    end
    return image_tag url, :class => "img-fluid rounded-circle " + cl, :width => size, :height => size
  end
end

app/views/layouts/_flash.html.haml
- if notice
  .alert.alert-info.alert-float
    = notice
    %button.close{"data-dismiss" => "alert", "aria-label" => "Close"}
      %span.icon-close{"aria-hidden" => "true"}
- if alert
  .alert.alert-warning.alert-float
    %span.icon-warning.mr-2
    = alert
    %button.close{"data-dismiss" => "alert", "aria-label" => "Close"}
      %span.icon-close{"aria-hidden" => "true"}

app/views/layouts/_footer.html.haml
%footer.container-fluid.mt-4.p-3.text-muted.text-center.bg-light
  footer

app/views/layouts/_header.html.haml
%nav.navbar.navbar-dark.bg-primary.navbar-expand-lg.fixed-top.pl-5
  .logo-fixed.rounded-circle
    = image_tag "logo.svg", :width => "30", :height => "30", :class => "d-inline-block align-top"

  = link_to root_path, :class => "navbar-brand ml-4" do
    Leaf
  %ul.navbar-nav
    %li.nav-item
      = link_to "Home", root_path, :class => "nav-link"
    %li.nav-item
      = link_to "Dashboard", manage_dashboard_path, :class => "nav-link#{ params[:controller] == "manage" ? " active" : ""}"
    %li.nav-item
      = link_to "Books", manage_books_path, :class => "nav-link#{ params[:controller] == "manage/books" ? " active" : ""}"
  %ul.navbar-nav.flex-row.ml-md-auto.d-none.d-md-flex
    - if current_user.author
      - @author = current_user.author
      %li.nav-item.dropdown
        = link_to "#", :class => "nav-link  dropdown-toggle",:id => "navbarDropdownMenuLink", "data-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" do
          = get_avatar(@author, 30, "mr-2")
          = @author.name
        .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdownMenuLink"}
          = link_to "个人信息", edit_profile_path, :class => "dropdown-item"
    %li.nav-item
      = link_to destroy_user_session_path, :method => :delete, :class => "nav-link", :title => "注销", "data-toggle" => "tooltip" do
        %i.fas.fa-sign-out-alt

app/views/layouts/_sidebar.html.haml
-#
  .text-center.mt-5
    - if @author = @author || current_user.author
      .mb-2
        = get_avatar(@author)
      %h4.card-title= @author.name
      .row
        .col
          .lead.text-primary
            %strong= author_count(@author)[:book]
          %p.mb-0
            %small.text-muted Books
        .col
          .lead.text-primary
            %strong= author_count(@author)[:post]
          %p.mb-0
            %small.text-muted Posts
  %hr
%nav.nav.nav-pills.flex-column.mt-5
  %li.nav-item
    = link_to manage_dashboard_path, :class => params[:action] == "dashboard" ? "nav-link active" : "nav-link" do
      %i.fa.fa-dashboard.mr-1
      Dashboard
  %li.nav-item
    = link_to manage_books_path, :class => params[:controller] == "manage/books" ? "nav-link active" : "nav-link" do
      %span.icon-book.mr-1
      书籍管理
  %li.nav-item
    = link_to "#", :class => "nav-link disabled" do
      %i.fa.fa-vcard.mr-1
      专栏管理
  %li.nav-item
    = link_to "#", :class => "nav-link disabled" do
      %i.fa.fa-comments.mr-1
      评论管理
  %li.nav-item
    = link_to "#", :class => "nav-link disabled" do
      %i.fa.fa-archive.mr-1
      资料集

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %title= yield(:title)
    = csrf_meta_tags
    = stylesheet_link_tag    'templates/paper', media: 'all', 'data-turbolinks-track': 'reload'
    //= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    = render 'layouts/flash'

    = javascript_pack_tag 'application'

app/views/layouts/application_admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %title= "Demo"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{:class => namespace_controller_name + " " + params[:action]}
    = render "layouts/header"
    .container-fluid.pt-5.flex-1
      .row
        .col-md-2
          = render "layouts/sidebar"
        .col-md-10
          = render "layouts/flash"
          = yield
    = render "layouts/footer"

app/views/layouts/application_editor.html.haml
!!!
%html
  %head
    %title BookApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.pt-5{:class => namespace_controller_name}
    = yield

app/views/layouts/application_manage.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %title= "Demo"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{:class => namespace_controller_name + " " + params[:action]}
    = render "layouts/header"
    .container-fluid.pt-5.flex-1
      -#
        .row
          .col-md-2.col-sm-3.sidebar.bg-white
            = render "layouts/sidebar"
          %main.col-md-10.col-sm-9.ml-sm-auto
      = yield
    //= render "layouts/footer"
    = render "layouts/flash"

app/views/layouts/editor.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %title= yield(:title)
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    //= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.pt-5{:class => namespace_controller_name}
    = yield

    = javascript_pack_tag 'editor'

app/views/layouts/manage.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %title= yield(:title)
    = stylesheet_link_tag    'application', media: 'all'
    //= javascript_include_tag 'application'
    = csrf_meta_tags
  %body{:class => namespace_controller_name + " " + params[:action]}
    = render "layouts/header"
    .container-fluid.pt-5.pb-3.flex-1.h-100
      -#
        .row
          .col-md-2.col-sm-3.sidebar.bg-white
            = render "layouts/sidebar"
          %main.col-md-10.col-sm-9.ml-sm-auto
      = yield
    //= render "layouts/footer"
    = render "layouts/flash"
    = javascript_pack_tag 'application'

app/views/layouts/session.html.haml
!!!
%html
  %head
    %title 登录
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body.login-bg
    .d-flex.flex-column.w-100.h-100.align-items-center.justify-content-center.login-mask
      %h1.text-center.mb-5.text-secondary.font-weight-normal
        = image_tag "logo.svg", :width => "80", :height => "80", :class => "align-bottom"
        Start for Writing?
      .card.w-50.border-0.shadow
        .d-flex
          .login-left.w-40.rounded-left
            .login-words.w-100.h-100.p-4.text-right.d-flex.rounded-left
              .align-self-end.w-100
                %p 生活就是
                %p 一本书
                %p 一壶茶
                %p 一个阳光明媚的下午
          .card-body.w-60.pt-5.pl-5.pr-5.pb-3
            = yield
      = render 'layouts/flash'